apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ballot
  name: {{ .Values.services.ballot.serviceName }}
  namespace: {{ .Values.namespace }}
spec: 
  selector: 
    app: ballot
  ports:
  - name: http
    port: {{ .Values.httpServicePort }}
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
  namespace: {{ .Values.namespace }}
  labels:
    createdby: divyesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
      - name: ballot
        image: '{{- printf "%s/%s:%s" .Values.registry .Values.services.ballot.imageName .Values.tag -}}'
        ports:
        - containerPort: 8080
