apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ecserver
  name: {{ .Values.services.ecserver.serviceName }}
  namespace: {{ .Values.namespace }}
spec: 
  selector: 
    app: ecserver
  ports:
  - name: http
    port: {{ .Values.httpServicePort }}
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecserver
  namespace: {{ .Values.namespace }}
  labels:
    createdby: divyesh

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecserver
  template:
    metadata:
      labels:
        app: ecserver
    spec:
      containers:
      - name: ecserver
        image: '{{- printf "%s/%s:%s" .Values.registry .Values.services.ecserver.imageName .Values.tag -}}'
        ports:
        - containerPort: 8081
